# Generated by Django 5.1 on 2024-08-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tar_file', models.FileField(blank=True, null=True, upload_to='uploads/tar')),
                ('pdb_file', models.FileField(blank=True, null=True, upload_to='uploads/pdb')),
                ('cif_file', models.FileField(blank=True, null=True, upload_to='uploads/cif')),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/img')),
            ],
        ),
    ]
