# Generated by Django 5.1 on 2024-08-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
