# Generated by Django 5.1 on 2024-09-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alphasum_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='alphasum',
            name='fasta_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/fasta'),
        ),
    ]
