# Generated by Django 5.1 on 2024-09-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alphasum_fasta_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='alphasum',
            name='unzipped',
            field=models.FileField(blank=True, null=True, upload_to='uploads/unzippped'),
        ),
    ]
