# Generated by Django 5.1 on 2024-09-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alphasum_unzipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alphasum',
            name='unzipped',
            field=models.FileField(blank=True, null=True, upload_to='uploads/unzipped'),
        ),
    ]
